---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dell.
--- DateTime: 2023/2/15 10:14
---
local l = redis.call('rpush', KEYS[1], ARGV[1])
local m = redis.call('hsetnx', KEYS[2], ARGV[2], ARGV[3])

return l + m