server:
  port: 9091


spring:
  application:
    name: batch-engine-plus
  dynamic:
    datasource:
      master:
        username: root
        password: 111111
        jdbc-url: jdbc:mysql://101.43.56.35:3306/engine?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      slave:
        username: root
        password: 111111
        jdbc-url: jdbc:mysql://101.43.56.35:3306/engine_customer?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  redis:
    host: 101.43.56.35
    port: 6379
    #password: 111111
    timeout: 30000
    database: 0
    jedis:
      pool:
        max-active: 10000
        max-idle: 9000
        min-idle: 9000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

engine:
  batch:
    #临时表前缀
    temp-table-pre: temp