---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dell.
--- DateTime: 2023/3/2 14:49
---

-- 表示注释
-- KEYS[1] 表示接收传入的第一个key参数
-- for循环插入数据
-- i=1表示从1开始，20表示截止，1表示递增值
if redis.call('exists', KEYS[1]) <= 0 then
    for i = 1, 10, 1 do
        -- 使用lpush向redis写入
        redis.call('lpush', KEYS[1], ARGV[1] .. '_' .. tostring(i))
    end
end
return "success"
-- 返回成功